import type { Metadata, Viewport } from "next";
import { Inter, Instrument_Serif, JetBrains_Mono } from "next/font/google";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { modeInitScript } from "@/lib/mode";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/Footer/Footer";
import EnvBanner from "@/components/EnvBanner/EnvBanner";
import JsonLd from "@/components/JsonLd";
import { organizationJsonLd, websiteJsonLd } from "@/lib/jsonLd";
import { isProductionEnv as isProductionEnvCheck } from "@/lib/env";
import "./globals.css";

// Indexability is decided by lib/env.ts (NEXT_PUBLIC_APP_ENV override →
// VERCEL_ENV → NODE_ENV). Only production indexes; preview / uat / dev all
// emit noindex,follow so internal-link signal still flows when the team
// shares a non-prod URL for review. <EnvBanner /> renders a visible stripe
// on every non-prod page so misconfigured envs are caught on first paint.
const isProductionEnv = isProductionEnvCheck();

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-inter",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

const SITE_URL = "https://reveren.ai";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "reveren — One pipeline. Every agent.",
    template: "%s · reveren",
  },
  description:
    "Structured, versioned, repo-aware guardrails for AI coding agents. Protocols plus pipelines that make whichever agent you already pay for dramatically better.",
  applicationName: "reveren",
  authors: [{ name: "reveren" }],
  keywords: [
    "AI coding agents",
    "protocols",
    "Claude",
    "Cursor",
    "Copilot",
    "Windsurf",
    "agent orchestration",
    "developer tools",
  ],
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "reveren",
    title: "reveren — One pipeline. Every agent.",
    description:
      "Stop correcting your AI. Start directing it. Structured guardrails for whichever coding agent you already use.",
    // OG image generated by app/opengraph-image.tsx (Next.js File Convention)
    // — Next auto-injects og:image referencing /opengraph-image. Slack /
    // LinkedIn / Twitter / Discord all render the PNG output, where the
    // previous SVG asset failed silently across those platforms.
  },
  twitter: {
    card: "summary_large_image",
    title: "reveren — One pipeline. Every agent.",
    description: "Stop correcting your AI. Start directing it.",
    // Twitter image inherits from openGraph.images (Next auto-bridges these).
  },
  icons: {
    icon: [{ url: "/logo/svg/reveren-favicon.svg", type: "image/svg+xml" }],
  },
  robots: isProductionEnv
    ? { index: true, follow: true }
    : {
        index: false,
        follow: true,
        googleBot: { index: false, follow: true },
      },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF8F5" },
    { media: "(prefers-color-scheme: dark)", color: "#141312" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${instrumentSerif.variable} ${jetbrainsMono.variable}`}
    >
      <body>
        {/*
          Sets data-mode on <html> before first paint so MUI's CSS vars
          resolve to the right palette on the first frame. Lives at the
          top of <body> (not <head>) because React 19's metadata Float
          reorders <head> children by kind (ld+json resources vs inline
          scripts), causing a hydration position-shift when this sat
          alongside the <JsonLd> scripts. A parser-blocking sync script
          at the start of <body> still runs before any body content paints.
        */}
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{ __html: modeInitScript }}
        />
        {/* Sitewide structured data. Rendered at the top of <body> (not
            <head>) for the same reason as the mode-init script above:
            React 19's <head> Float — and head-injecting browser extensions —
            shift the position of inline/ld+json <script>s in <head> and trip
            hydration. JSON-LD is valid anywhere in the document and search
            engines read it from <body>. Per-page JSON-LD already renders here. */}
        <JsonLd data={organizationJsonLd()} />
        <JsonLd data={websiteJsonLd()} />
        <EnvBanner />
        <ThemeRegistry>
          <a href="#main" className="rv-skip-link">
            Skip to content
          </a>
          <Nav />
          <main id="main">{children}</main>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}

