// Release history for the public /changelog page.
//
// Cross-repo sync: the source of truth for a published version is the
// CHANGELOG.md generated by changesets in @reveren-ai/core. When a release is
// cut (see core's RELEASING.md), add the matching entry here so the site
// reflects what's live on npm. Keep newest-first.

export type ReleaseStatus = "released" | "upcoming";

export type Release = {
  version: string;
  /** Human date for released versions, or "Upcoming" while in build. */
  date: string;
  status: ReleaseStatus;
  summary: string;
  highlights: string[];
};

/** The version the page badges as current. Matches the latest released entry. */
export const CURRENT_VERSION = "0.1.0";

export const releases: Release[] = [
  {
    version: "0.1.0",
    date: "Upcoming",
    status: "upcoming",
    summary:
      "The first real CLI. One command drops a versioned protocol library into any repo so every coding agent works from the same rules.",
    highlights: [
      "`rvr init` scaffolds protocols.config.ts, the .protocols/ library, and the host package.json wiring.",
      "`rvr run <protocol>` prints any protocol — or the bundled coordinator agent — for the active agent to ingest.",
      "`rvr list` and `rvr check` round out the surface; `rvr sync` is stubbed for the Phase 2 registry.",
      "15 bundled protocols plus the coordinator agent — the pipeline orchestrator that chains protocols into design → implement → review → QA → document → ship.",
      "Open .protocols/ format spec published; CLI is source-available under BUSL-1.1.",
    ],
  },
  {
    version: "0.0.1",
    date: "May 2026",
    status: "released",
    summary:
      "Reserved-scope placeholder published to npm to secure the @reveren-ai/core name ahead of the real CLI.",
    highlights: [
      "Canonical scope @reveren-ai/core and defensive scope @reveren/core reserved on npm.",
    ],
  },
];
